# Generated by Django 4.0.4 on 2022-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_randoop', '0002_rename_username_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_codes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
