# Generated by Django 4.0.4 on 2022-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_randoop', '0004_rename_date_user_codes_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_codes',
            name='used_tool',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
