# Generated by Django 4.0.4 on 2022-06-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_randoop', '0005_user_codes_used_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_codes',
            name='class_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
